### PR TITLE
Update simple pp counter by Inlayo

### PR DESCRIPTION
**Pull request by Inlayo**
:D

### CODE REVIEW

**Comment by cyperdark** [comment]
what is changed?

**Comment by Inlayo** [comment]
Remove unnecessary code and fixed issue of PP not being applied during the song selection process.

**Comment by cyperdark** [comment]
you overwrote changes i applied resently and now you code still have unnecessary code
image


redownload counter from github, and update the code in here to show pp in menu

**Comment by Inlayo** [comment]
Without ifFcpp, the full combo pp value doesn't appear on the song selection screen 😭

**Comment by cyperdark** [comment]
dont replace new code with your old one, download version from the master and make your changes in that code

clicke here download https://github.com/tosuapp/counters/tree/master/counters/simple%20pp%20counter%20by%20Inlayo
and then change things here

**Pull request closed without merging**
