### PR TITLE
new: simple pp counter

### PR DESCRIPTION
**Pull request by Inlayo**
simple PP counter was a complete mess, so I fixed it and made a new Inlayo PP counter.

### CODE REVIEW

**Comment by cyperdark** [comment]
@Inlayo image/video preview please

**Comment by Inlayo** [comment]
The appearance is the same as https://github.com/tosuapp/counters/tree/master/counters/simple%20pp%20counter%20by%20Inlayo, but it's the code with the broken parts fixed.

**Comment by Inlayo** [comment]
simple pp counter by inlayo
simple pp counter by inlayo
ヾ(≧▽≦*)o

**Comment by Inlayo** [comment]
okay :3

**Comment by cyperdark** [comment]
@Inlayo if it's fix for old one, then use the same folder name
```
simple pp counter by Inlayo
```

**Comment by Inlayo** [comment]
:D

**Pull request closed without merging**
